version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  php:
    container_name: laravel_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html # Mount your PHP project into /var/www/html
    user: 1000:1000
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: laravel_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
    networks:
      - laravel

  # Used to view and interact with DB.
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8083:8080
    networks:
      - laravel

volumes:
  db: